version: v2beta1
name: app

vars:
  NODE_VERSION:
    source: env
    default: "20.10.0"
  GID:
    source: env
  UID:
    source: env

commands:
  k3d:
    command: |-
      k3d cluster create || true
      kubectl create namespace app || true
      kubens app
      devspace use namespace app

deployments:
  app:
    kubectl:
      manifests:
        - ./k8s
      kustomize: true

dev:
  app:
    imageSelector: app
    logs:
      enabled: true
    ports:
    - port: 3000:3000
    open:
      - url: http://localhost:3000
    command: ["bash", "-c", "yarn && yarn dev"]
    sync:
      - path: ./:/home/user/app
        startContainer: true
        initialSync: mirrorLocal
        waitInitialSync: true

images:
  app:
    image: app
    buildArgs:
      NODE_VERSION: "20.10"
    dockerfile: ./Dockerfile
    context: ./
    target: dev
    tags:
      - latest
    rebuildStrategy: default 
    skipPush: true

pipelines:
  deploy:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all -t $(git describe --always)
      create_deployments --all
  dev:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all -t $(git describe --always)
      create_deployments --all
      start_dev --all
